In [1]:
import numpy as np

## Задание 1

Создайте numpy array с элементами от числа N до 0

In [28]:
a = np.arange(0, int(input("Введите число N: ")), 1)[::-1]
a 

Введите число N: 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [46]:
b = np.diag(np.arange(1,5)[::-1], -1)
b[1::,:-1:] # диагональная матрица, 
np.trace(b[1::,:-1:]) # сумма значений на диагонали

10

## Задание 3

Решите систему уравнений:

In [11]:
m1 = np.array([[4., 2., 1.], [1., 3., 0.], [0., 5., 4.]]) #левая часть системы
v1 = np.array([4., 12., -3.]) #правая часть системы
np.linalg.solve(m1, v1)

array([ 0.46666667,  3.84444444, -5.55555556])

## Задание 4


In [53]:
# Матрица покупок в интернет-магазине
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
users_stats

array([[2, 1, 0, 0, 0, 0],
       [1, 1, 2, 1, 0, 0],
       [2, 0, 1, 0, 0, 0],
       [1, 1, 2, 1, 0, 1],
       [0, 0, 1, 2, 0, 0],
       [0, 0, 0, 0, 0, 5],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 3],
       [1, 0, 0, 2, 1, 4]])

In [52]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
next_user_stats

array([0, 1, 2, 0, 0, 0])

In [91]:
# Поиск самого похожего пользователя 
cos_sim_all = []
for i in users_stats:
    cos_sim = np.dot(next_user_stats, i) / (np.linalg.norm(next_user_stats) * np.linalg.norm(i))
    cos_sim_all.append(cos_sim)
    sort = np.argsort(cos_sim_all)
print(f"Самый похожий пользователь (ID): {sort[-1]+1}. Косинусное сходство между векторами {cos_sim_all[sort[-1]]}")

Самый похожий пользователь (ID): 8. Косинусное сходство между векторами 0.9486832980505138
